<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

|Term|Breif description|
|:--|--:|
|Subsetting|is the goal that is obtaining a specific portion of data from the dataset|
|Indexing|retrieving an element through its index, this coould be from lists arrays or dictionaries|
|Slicing|getting a chunk of the data which is many indexes by using the index|
|Masking|retrieving the data that fulfils certian conditions by constructing a new variable to contain all the boolean values generated from the sorting of the data. Is used in subsetting by putting the variable in [] as python understands to extract only the true|


In [2]:
#This could probably have been done better

import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

first_elements_array = np_array_2d[:,0] #choses the element in position 0 for each set of data from 0 to 10
print(first_elements_array)

masked_array = first_elements_array.astype(int) #changes the datatype of the array of numbers to integer
print(masked_array)

intermediate_array = masked_array % 2 #gets the ones that are not odd

if intermediate_array.any != 0:
    print(intermediate_array) #check for correctness
    indexes = np.where(intermediate_array)[0] #finds the index where the "True"s are 
    second_element_array = np_array_2d[indexes,1] #uses the indexes found to isolate the sets we want, and takes out the position 1 of each of these sets
    print(second_element_array)
else:
    print("IT RUNS") #because my code didnt even run before this T-T


['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]
['A' 'C' 'E' 'G' 'I']


In [1]:
import numpy as np
givenlist = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

givenarray = np.array(givenlist)
givenarray.astype(int)

givenarray[givenarray < 50] = -1
print(givenarray) #we run this first because we dont want the later 1 to be affected since its smaller than 50

givenarray[givenarray > 50] = 1
print(givenarray)

givenarray[givenarray == 50] = 0
print(givenarray)

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]
[[ 1 50  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [ ]:
#good to know optional 
hannah = ['h','a','n','n','a','h']
nus = ['n', 'u', 's']
print(nus[::-1])
print(hannah[::-1])
print(hannah[5::-1]) #the issue is the 0 because this syntax is not inclusive of the 0


['s', 'u', 'n']
['h', 'a', 'n', 'n', 'a', 'h']
['h', 'a', 'n', 'n', 'a', 'h']
