<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

|Question|Answer|
|:--|--:|
|Two similarities between lists and arrays.|*both are used to store multiple elements, and both can be iterated through(corrected)*|
|Two differences between lists and arrays.|*lists are [], arrays are lists within () so you can have multiple sets of data, data types are impt in arrays but not so much in lists*|
|What is a dictionary?|*defines multiple items in a singular line of code. Can be modified*|


In [ ]:
import numpy as np

ans = np.sqrt(4)
print(int(ans))


2.0


In [ ]:
function = f'{0.3:.17f}' #the f means decimal places, the colon is a format separator
print(function)

0.29999999999999999


In [3]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])    # Prints 'a1'
print(py_list[2])    # Prints 'c3'
print(py_list[4])    # Prints 'e5'
print(py_list[-4])   # Prints 'g7'
print(py_list[-2])   # Prints 'i9'

a1
c3
e5
g7
i9


In [5]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']
print(elements[4])
print(elements[-6])

Boron
Boron


In [ ]:
import numpy as np
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_array = np.array(numbers)

no_of_one = numbers.count(1)
print(no_of_one)

ones = np.sum(np_array == 1)
print(ones)



9
9


In [26]:
import numpy as np

x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

x1array = np.array(x_1) #converts list to array
x2array = np.array(x_2) #converts list to array 

mean1 = np.mean(x1array) #mean 
mean2 = np.mean(x2array) #mean
print(f"the mean of x_1 is {mean1}")
print("the mean of x_2 is", mean2)

stdv1 = np.std(x1array)
stdv2 = np.std(x2array)
print(int(stdv1),"(nearest whole)") #standard deviation to the nearest whole
print(int(stdv2),"(nearest whole)") #standard deviation to the nearest whole

cov1 = np.cov(x1array, x2array)
print (cov1)

check1 = np.corrcoef(x_1, x_2)
print(check1)

r_value_try1 = cov1 / (stdv1*stdv2)
print(r_value_try1)

r_value_try2 = (sum((x1array - np.mean(x1array)) * (x2array - np.mean(x2array)))) / (np.sqrt((sum((x1array - np.mean(x1array))**2)) * (sum((x2array - np.mean(x2array))**2)))) #counting brackets properly is very impt
print (r_value_try2)



the mean of x_1 is 38.5
the mean of x_2 is 302.5
32 (nearest whole)
326 (nearest whole)
[[  1167.83333333  11595.83333333]
 [ 11595.83333333 118149.16666667]]
[[1.         0.98717966]
 [0.98717966 1.        ]]
[[ 0.11046701  1.09686629]
 [ 1.09686629 11.17589694]]
0.9871796626270701


In [ ]:
#corrections oops this was not masking 

import numpy as np
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_array = np.array(numbers)

ones = 0
for i in np_array:
    if i == 1:
        ones += 1 #else do nothing haha i dont need it so just skip
print(ones)

9


In [ ]:
#horribly done masking for learning please ignore  
import numpy as np 
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
numbers_array = np.array(numbers)

listofones = numbers_array == 1
print(listofones)
countones = numbers_array[listofones] #selects for the true
len(countones)


[False False  True False False  True False False False  True False False
 False False False False False  True  True False False False False False
 False False False False  True False  True False False False False False
  True False False False False False False  True False False False False
 False False]


9

In [ ]:
#corrections (better done masking) pls look at this one instead
import numpy as np 
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
numbers_array = np.array(numbers)

countingarray = numbers_array[numbers_array == 1] #selects for indexes where the numbers are 1 basically shortens the previous code 
print(countingarray)
len(countingarray)


[1 1 1 1 1 1 1 1 1]


9

In [ ]:
#corrections for exercise 2 (using slicing)
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

